# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
# theme: jekyll-theme-architect
title: Cotwelf's homepage
description: 每日三省吾身，学习了吗？学习了吗？？学习了吗？？？
subtitle: ''
keywords:
author: John Doe
language: en
timezone: ''
